# Generated by Django 3.1.5 on 2021-02-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TacheLongCours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nom',
            new_name='name',
        ),
    ]
