# Generated by Django 3.1.5 on 2021-02-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TacheLongCours', '0003_tache_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='date_tache',
            field=models.DateTimeField(verbose_name='Date de tâche'),
        ),
    ]
