# Generated by Django 3.1.5 on 2021-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TacheLongCours', '0004_auto_20210203_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='date_creation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_tache',
            field=models.DateField(blank=True, verbose_name='Date de tâche'),
        ),
    ]
