# Generated by Django 3.1.5 on 2021-02-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TacheLongCours', '0006_auto_20210203_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
