# Generated by Django 3.1.5 on 2021-02-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TacheLongCours', '0008_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='slug',
        ),
    ]
