# Generated by Django 3.1.5 on 2021-02-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TacheLongCours', '0009_remove_tache_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDeTache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tache',
            name='type_de_tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TacheLongCours.typedetache'),
        ),
    ]
