# Generated by Django 3.1.5 on 2021-02-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TacheLongCours', '0012_auto_20210204_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='type_de_tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TacheLongCours.typedetache', verbose_name='Type'),
        ),
    ]
