# Generated by Django 3.1.5 on 2021-02-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TacheLongCours', '0013_auto_20210204_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
